runtime: python27
threadsafe: true

handlers:
- url: /app
  script: app.app
- url: /
  static_files: static/html/index.html
  upload: static/html/index.html
  mime_type: text/html
- url: /(.*)
  static_files: static/\1
  upload: static/(.*)
