# see how to configure thigns here in:
# https://cloud.google.com/appengine/docs/standard/python3/config/appref
runtime: python37

# cache expiration time, default is 10 min
default_expiration: "10d"

handlers:
- url: /static/
  static_dir: static/
  secure: always
- url: /app/
  script: auto
  secure: always
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
  secure: always
- url: /
  static_files: static/html/index.html
  upload: static/html/index.html
  secure: always
