runtime: python37

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  secure: always
- url: /app/.*
  script: auto
  secure: always
- url: /static/html/index.html
  static_file: static/html/index.html
  mime_type: text/html
  secure: always
- url: /static
  static_dir: static/
  secure: always

skip_files:
- ^\.git/.*
- ^.idea/.*
- ^node_modules/.*
- ^tools/.*
- ^\.venv/.*
- ^support/.*
- ^db/.*
- ^misc/.*
- ^out/.*
- ^datastore/.*
- ^gcloud/.*
- ^config/.*
- ^tests/.*
- ^doc/.*
- ^(.*/)?.*\.py[co]$
- ^Makefile$
- ^README\.md$
- ^package\.json$
- ^requirements\.txt$
- ^\.gitignore$
- ^\.gcloud$
- ^\.myenv$
