application: nikuda-web
runtime: python
runtime_config:
        python_version: 3
threadsafe: true

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /images
  static_dir: images
- url: /js_tp
  static_dir: js_tp
- url: /python/(.+)\.py
  script: /python/\1.py
- url: /(.*).ico
  static_files: images/\1.ico
  upload: images/.*
- url: /
  static_dir: html
