application: nikuda-web
version: 1
runtime: php
api_version: 1

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /images
  static_dir: images
- url: /js_tp
  static_dir: js_tp
- url: /php
  static_dir: php
- url: /
  script: php/index.php
