runtime: python37

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
- url: /app/.*
  script: auto
- url: /static/html/index.html
  static_files: static/html/index.html
  upload: static/html/index.html
  mime_type: text/html
- url: /static
  static_dir: static/

