application: nikuda-web
version: 1
runtime: php55
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /images
  static_dir: images
- url: /js_tp
  static_dir: js_tp
- url: /php/(.+)\.php
  script: /php/\1.php
- url: /
  script: php/index.php
- url: /favicon.ico
  static_files: images/favicon.ico
